# use beeeeeg numbers so they're easier to tweek. 
# We can scale them elsewhere to keep them inside a reasonable range while giving us reasonable granularity here for balancing.

# Stores Player Configs
[Player]
Speed = 1
JumpHeight = 1

# Stores UI Configs
[UI.Resolution]
X = 1
Y = 1

# Stores Game Configs
[Game]
bar = "test"